### PR TITLE
Prevent memory leak by removing cyclical reference. See #4392.

### PR DESCRIPTION
**Pull request by almathew**
In paramiko, channel references transport and transport references channel. This means that the objects never get freed after they're used. A new one of these gets created every time someone connects to our SFTP servers, resulting in a LOT of these objects hanging around taking up space.
## Description

Switches the reference to a weak reference so the objects can actually be collected. 
## Motivation and Context

Assembla Ticket Link: #4392

This is required to solve a memory leak in our SFTP servers.
## How has this been tested?

Manually by both @UserNotFound and I.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] The code follows the [code style](https://github.com/smartfile/smartfile/wiki/Development-%28Coding-Standards%29) of this project.
- [ ] Documentation has been updated accordingly.
- [ ] Tests are sufficient and verify acceptance criteria.

### CODE REVIEW

**Comment by almathew** [comment]
I'm open to other options for solving this. I'm not committed to doing it this way, I just  tried one or two proposed fixes for this issue and this was the only one that actually worked for me.

**Comment by travcunn** [comment]
Is this a fix we should fix upstream in the [paramiko/paramiko](https://github.com/paramiko/paramiko) project?

**Comment by almathew** [comment]
I actually stole it from a proposed fix:
https://github.com/paramiko/paramiko/pull/367/

**Comment by travcunn** [comment]
This should be OK for our purposes. It would probably be preferable to fix the cyclical reference rather than using `weakref` but we can investigate that later.

Make sure you open a PR to update our repos that use this library.

**Pull request merged**
